### ISSUE TITLE
Nullpointer in HTTPClient class

### ISSUE THREAD

**Issue by LumpyTales** [amadeus4dev/amadeus-java#78]
## Description

If you call the Amadeus next-function without a response object which contains a meta-element (which is usually the case after you retrieved the last bunch of data) a Nullpointer is raised.

```
java.lang.NullPointerException: null
at com.amadeus.resources.Resource.fromArray(Resource.java:31) ~[amadeus-java-5.0.0.jar!/:5.0.0]
at com.amadeus.HTTPClient.page(HTTPClient.java:445) ~[amadeus-java-5.0.0.jar!/:5.0.0]
at com.amadeus.HTTPClient.next(HTTPClient.java:293) ~[amadeus-java-5.0.0.jar!/:5.0.0]
```

Seems to be that this line in [HTTPClient](https://github.com/amadeus4dev/amadeus-java/blob/322873442677c25b547532c57ed024987568807d/src/main/java/com/amadeus/HTTPClient.java#L435) is the problem. Because then in here [HTTPClient](https://github.com/amadeus4dev/amadeus-java/blob/322873442677c25b547532c57ed024987568807d/src/main/java/com/amadeus/HTTPClient.java#L445) the Nullpointer is raised.

## Steps to Reproduce

1. Call amadeus.shopping.hotelOffers.get() with limit
2. Call amadeus.next function in a loop
3. after you got the last result you will not get any meta-json-element in the response-result object which produces in the following amadeus-next call a nullpointer. 

__Expected Behavior:__ No NullPointer. :-) 
Would expect that the result of amadeus.next is null in this case. Or maybe better return a List instead of an array and use Collections.emptyList();

__Actual Behavior:__ Nullpointer

__Stable Behavior?__ No. 100% chance to hit it if you load the full data which is a common case.

## Versions

OpenJDK / Docker Linux

## Checklist

Please make sure you checked the following:

* Did you download the latest version of this library? yes

**Comment by LumpyTales** [comment]
As there is no progress ... its closed
